# -*- coding: utf-8 -*-
"""Lesson5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t3Nw_fSn2ac3J05qKHzpklxwxwj8dICW

#Lesson 5: Object Oriented Programming
#Author: Arnav Maskey

Topic: Object Oriented Programming

Basic Python Class Example

1. Introduction to Object-Oriented Programming

Object-oriented programming is a programming paradigm based on the concept of "objects", which can contain data and code: data in the form of fields (often known as attributes), and code, in the form of procedures (often known as methods).

Object-oriented programming and the use of objects in programming offer several significant advantages:

**Modularity:** Objects help in building isolated modules or chunks of code. Each object is a self-contained unit. This modularity makes it easier to troubleshoot and maintain code, as changes to one object do not directly impact other parts of the program.

**Encapsulation:** Objects encapsulate data and the methods that operate on that data. This means that the internal workings of an object can be hidden from the outside world. It's a way of restricting access to certain aspects of an object while exposing a controlled interface for interacting with it.

**Reusability:** Objects can be reused across different parts of a program or even in different programs. This is achieved through inheritance, where a new class can inherit properties and methods from an existing class. Reusability saves time and effort as developers can use existing, tested, and debugged code.

**Scalability:** Object-oriented programs are more scalable, making it easier to manage larger applications. As new objects can be created with small differences to existing ones, OOP is very useful for large, complex, and actively updated or maintained software.

**Design Benefits:** Object-oriented design principles promote better organization of code and a clearer, more logical structure. This can lead to more efficient and effective problem-solving and development processes.

2. Defining a Class

A class in Python is like a blueprint for creating objects. Each class should represent a single concept or thing.
"""

class Dog:
    """A simple dog class."""

    def __init__(self, name, age):
        """
        Initialize name and age attributes.
        :param name: string, name of the dog
        :param age: int, age of the dog
        """
        self.name = name
        self.age = age

    def sit(self):
        """Simulate a dog sitting in response to a command."""
        print(f"{self.name} is now sitting.")

    def roll_over(self):
        """Simulate rolling over in response to a command."""
        print(f"{self.name} rolled over!")

"""3. Creating an Object

Now, let's create an instance (object) of the `Dog` class.

"""

my_dog = Dog("DogName", 12)
#Here, `my_dog` is an instance of the `Dog` class.

"""4. Accessing Attributes

You can access the attributes of an instance using the dot notation.

"""

print(f"My dog's name is {my_dog.name}.")
print(f"My dog is {my_dog.age} years old.")

"""5. Calling Methods

You can also call methods defined in the class.

"""

my_dog.sit()
my_dog.roll_over()

"""6. Adding Complexity

As you get more comfortable, you can add more methods and attributes to the class. For example, you might add a `breed` attribute, or a method to `bark`.

"""

class Dog:
    #A more complex dog class

    def __init__(self, name, age, breed):
        """Initialize name, age, and breed attributes."""
        self.name = name
        self.age = age
        self.breed = breed

    # Existing methods...

    def bark(self):
        """Simulate a dog barking."""
        print(f"{self.name} says Woof!")