# -*- coding: utf-8 -*-
"""Lesson3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18BkcB7aBPMN52b6BIsNEEA6HnR2ODP7H

#Lesson 3: Numpy
#Author: Arnav Maskey
"""

#############################
#Basic Overview:

#Array Creation

import numpy as np
a = np.array([1, 2, 3])
print(a)

#Basic Operations**:

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # Element-wise addition
print(a * b)  # Element-wise multiplication

#Indexing and Slicing**:

import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1, 2])  # Outputs 6
print(a[:, 1])  # Outputs [2 5 8]

#############################
#Intermediate Level:

#Reshaping Arrays
#Refers to changing the structure (i.e., the number of rows, columns, and possibly more dimensions) of an array without changing its data.

import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(3, 2)
print(b)

#Matrix Multiplication

import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [0, 2]])
result = np.dot(a, b)
print(result)

#############################
#Advanced Level:

#Eigenvalues and Eigenvectors
import numpy as np
a = np.array([[4, 2], [2, 4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

#Broadcasting

import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 0, 1])
result = a + b
print(result)

### Documentation:

#For a comprehensive understanding and detailed documentation, you can refer to the official [NumPy documentation](https://numpy.org/doc/).
#This documentation provides in-depth explanations, more examples, and advanced functionalities of NumPy.